# Generated by Django 5.1.6 on 2025-07-11 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='school',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
