# Generated by Django 5.1.6 on 2025-07-09 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('minigames', '0001_initial'),
        ('questions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='assessmentitem',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minigames.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentitem',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
        migrations.AddField(
            model_name='assessmentitemresult',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='minigames.assessmentitem'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='minigame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minigames.minigame'),
        ),
    ]
