# Generated by Django 5.1.6 on 2025-07-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minigame',
            name='challenges',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='minigame',
            name='lives',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='minigame',
            name='short_description',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minigame',
            name='time_limit_seconds',
            field=models.IntegerField(blank=True, help_text='Seconds (null = no time limit)', null=True),
        ),
        migrations.AddField(
            model_name='minigame',
            name='tips',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='minigame',
            name='instructions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
