# Generated by Django 5.1.6 on 2025-07-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0003_minigame_challenges_minigame_lives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minigame',
            name='challenges',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='minigame',
            name='lives',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='minigame',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
