# Generated by Django 5.1.6 on 2025-07-09 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.adminprofile'),
        ),
        migrations.AddField(
            model_name='readingcontent',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.levelzone'),
        ),
        migrations.AddField(
            model_name='topic',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.levelzone'),
        ),
        migrations.AddField(
            model_name='readingcontent',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.topic'),
        ),
        migrations.AddField(
            model_name='pdf',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.topic'),
        ),
    ]
