# Generated by Django 5.1.6 on 2025-07-11 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_level_topic_zone_topic_embedding_topic_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='embedding',
        ),
        migrations.DeleteModel(
            name='SubTopic',
        ),
    ]
